### ISSUE TITLE
HTML and CSS 

### ISSUE THREAD

**Issue by Jesim0** [RitikPatni/Front-End-Web-Development-Resources#133]
Hello! I just finished learning HTML and CSS.... Don't know how to go about starting a web development (guide) ... Which type of web development is suitable to only HTML & CSS learning alone, without learning Javascript for now....

**Comment by RitikPatni** [comment]
@Jesim0 You can try beginner problems from https://www.frontendmentor.io/ or try https://freecodecamp.org/ responsive web design certificate projects.

**Comment by Jesim0** [comment]
Thank you sir.. This is very helpful... Thanks a lot
