### ISSUE TITLE
Web Development Resource Adding 

### ISSUE THREAD

**Issue by Subhampreet** [RitikPatni/Front-End-Web-Development-Resources#136]
I would like to add few more resources to the list which are some of the best ones I know to learn new frameworks and Libraries. Hope the repository is accepting contributions.

**Comment by RitikPatni** [comment]
@Subhampreet Yeah feel free to add anything that improves the repository.

**Comment by suddhasattwakhan** [comment]
Sir I have added an amazing youtube channel in your readme. Please merge them if you like the recommendation @RitikPatni  sir.
