### ISSUE TITLE
Happy Hacktoberfest!!

### ISSUE THREAD

**Issue by RitikPatni** [RitikPatni/Front-End-Web-Development-Resources#16]
Thanks to hacktoberfest that I got a positive response to the resource library.Now we have enough resources.So I need some help to refactor these resources.Here is a checklist of things that are required to make this repository more beneficial to newbies.
## Changes Requested
- [x] Add resources to repository **You can still add more**
- [x] Add Table of Contents which can navigate through all the resources

- [x]  Add context to each resource so that users can know about the resource

- [x] Add context to each section

- [x] Rearrange resources in each category in an alphabetical manner

**Happy HacktoberFest**

**Comment by Miffili** [comment]
Hey!

Just wanted to let you guys know, I'm working on adding context to each resource. If anyone wants to help?

I'm opening a pull request with what I've done so far. ☺

**Comment by RitikPatni** [comment]
The list looks outdated in today's context so if anyone looking for repositories to contribute for hacktoberfest. Then this might be a good place.

Our main tasks would be 
* Add new content which you find useful for yourself while making sure that it isn't already there
* If you think any of the content is already there but is now deprecated then you can help in refactoring that as well. **Please also add an explanation while submitting a pull request as to why you don't think the content is useful anymore**
* Improve content description. So it is more meaningful for users

Content is live for preview at [Resources](https://resources.ritikpatni.me/) 

**Happy Hacktoberfest** 🎉🎉
