### ISSUE TITLE
Put free or paid badges based on content

### ISSUE THREAD

**Issue by RitikPatni** [RitikPatni/Front-End-Web-Development-Resources#81]
Help me put up free or paid badges based on the content available
Badges to be used 
 ![Free](https://img.shields.io/badge/-Free-brightgreen)
 ![Paid](https://img.shields.io/badge/-Paid-blue)

**Note: Add both the badges if some content is free and the rest is paid**

**Comment by NishithP2004** [comment]
Hi, I would love to work on this issue.. Could you please assign me to this issue?

And for sake of clarity, Should the labels be added beside the name of the resource or the main category of the resource in the README.MD file..?

:)

**Comment by NishithP2004** [comment]
Thanks, Is there any time limit by when I should submit my PR (although I will have it ready in a short while) and will it be merged only on October 1st for Hacktoberfest Statistics.

**Comment by RitikPatni** [comment]
I think it should be already open now and all contributions made from now on should be counted although to be on a safer side you can make the PR on October 1. It doesn't matter whether the PR is merged or not as long as the author doesn't mark it invalid or spam in 7-10 days since submitting. 

You can check this out for more info https://hacktoberfest.digitalocean.com/faq
